# Base settings

# enable true color mode (on mac and linux)
# see https://github.com/tmux/tmux/issues/2665#issuecomment-825017707
set-option -gs default-terminal "tmux-256color"
set-option -gas terminal-features "xterm-256color:RGB"

# # Enable True Color and RGB support
# set-option -gas terminal-overrides "*:Tc"
# set-option -gas terminal-overrides "*:RGB"

# Fix for drawing issues in devpod ssh sessions
set -ag terminal-overrides ',*:cud1=\E[1B'

# Enable double/curly underline
set-option -gas terminal-overrides '*:Smulx=\E[4::%p1%dm'
set-option -gas terminal-overrides '*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# The one true leader key
set -g prefix C-b

# Enable mouse mode
set -g mouse on

# Get things like shift+enter to work maybe?
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Fix Mouse Scrolling: https://github.com/tmux/tmux/issues/145
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# Using vim with tmux can cause a delay with escape, that's terrible
set -sg escape-time 0

# don't rename windows automatically
# C-b , to rename window
set-option -g allow-rename off

# 1 indexed instead of zero
setw -g pane-base-index 1
set -g base-index 1

set -g focus-events on # from vim checkhealth
set -g set-clipboard on

# More scrollback
set -g history-limit 100000

# Movement
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n C-Left previous-window
bind -n C-Right next-window

# Bind panes so I can type the same command in everything
bind -n M-g setw synchronize-panes on
bind -n M-o setw synchronize-panes off

bind c new-window      -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

######################
### DESIGN CHANGES ###
######################

# Quiet — no activity bells or visual noise
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# The modes
setw -g clock-mode-colour colour135
setw -g mode-style fg=colour196,bg=colour238,bold

# The panes
set -g pane-border-style bg=colour235,fg=colour238
set -g pane-active-border-style bg=colour236,fg=colour51

# The statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style bg=colour234,fg=colour137,dim
set -g status-interval 2
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour245,bold] %A %-I:%M #[fg=colour255,bg=colour000] #(whoami)@#H'
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style fg=colour81,bg=colour238,bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-style fg=colour138,bg=colour235,none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-style fg=colour255,bg=colour1,bold

# The messages
set -g message-style fg=colour232,bg=colour166,bold
